name: nem.ec
description: A coder with a fascination for etymology and diversity in tech.
url: https://blog.nem.ec

production: true

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

exclude:
  - "*.bak"
  - "tasks"

gems:
  - jekyll-sitemap
