name: nem.ec
description: "..."
url: https://blog.nem.ec

production: true

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

collections:
  code-snippets:
    output: true
    slug: "code-snippets"
  tools:
    output: true
    slug: "tools"

exclude:
  - "*.bak"
  - "tasks"

plugins:
  - jekyll-sitemap
  - jekyll-target-blank