name: Dan Nemec
description: A coder with a fascination for etymology and diversity in tech.
url: https://blog.nem.ec

markdown: kramdown
pygments: rouge
permalink: /:year/:month/:day/:title/

exclude:
    - "*.bak"

gems:
  - jekyll-sitemap
