name: Dan Nemec's Blog
description: A coder with a fascination for etymology and diversity in tech.
url: http://127.0.0.1:4000

production: false

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

exclude:
  - "*.bak"
  - "tasks"

gems:
  - jekyll-sitemap
