name: Dan Nemec
description: A coder with a fascination for etymology and diversity in tech.
url: https://blog.nem.ec

markdown: redcarpet
pygments: true
permalink: /:year/:month/:day/:title/

gems:
  - jekyll-sitemap
