#!/usr/bin/env ruby

require 'html-proofer'

options = {
  :typhoeus => { 
    :timeout => 5,
    :verbose => true },
  :assume_extension => true
}
HTMLProofer.check_directory("./_site", options).run
